title: Abdirayimov Sardor
email: abdirayimovsardor20[at]gmail[dot]com
description: Machine Learning Engineer
baseurl: "https://abdirayimovs.github.io/" 
url: "https://abdirayimovs.github.io/" 
github_username:  AbdirayimovS
linkedin_username: sardorabdirayimov


show_excerpts: false


header_pages:
- home.html
- about.html
- projects.html


# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
