title: Abdirayimov Sardor
email: abdirayimovsardor@gmail.com
description: the darkest nights produce the brightest stars
baseurl: ""
url: "https://abdirayimovs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AbdirayimovS
github_username:  AbdirayimovS
telegram_username: Sardor2o18
kaggle_username: sardorabdirayimov


# Build settings
theme: minima
plugins:
  - jekyll-feed
