title: Abdirayimov Sardor
email: sardor@gmail.com
description: "The ability to ask the right question is more than half the battle of finding the answer. 
- Thomas J.Watson"
baseurl: ""
url: "https://abdirayimovs.github.io/" 
twitter_username: AbdirayimovS
github_username:  AbdirayimovS
linkedin_username: sardorabdirayimov
kaggle_username: sardorabdirayimov


show_excerpts: true


header_pages:
- home.html
- about.html
- projects.html
- awards.html
- memories.html


# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
